//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWebs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atencion
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<int> Mascota { get; set; }
        public Nullable<int> Examen { get; set; }
        public Nullable<int> Desparacitacion { get; set; }
        public Nullable<int> Vacuna { get; set; }
    
        public virtual Desparacitacion Desparacitacion1 { get; set; }
        public virtual Examen Examen1 { get; set; }
        public virtual Mascota Mascota1 { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual Vacuna Vacuna1 { get; set; }
    }
}
