//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWebs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.Atencion = new HashSet<Atencion>();
            this.Desparacitacion = new HashSet<Desparacitacion>();
            this.Examen = new HashSet<Examen>();
            this.Vacuna = new HashSet<Vacuna>();
        }
    
        public int Microchip { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public decimal Peso { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<bool> Esterilizado { get; set; }
        public Nullable<bool> Defuncion { get; set; }
        public Nullable<System.DateTime> FechaDef { get; set; }
        public string CausaDef { get; set; }
        public string ObserDef { get; set; }
        public Nullable<int> Rut { get; set; }
        public Nullable<int> Especie { get; set; }
        public Nullable<int> Raza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atencion> Atencion { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desparacitacion> Desparacitacion { get; set; }
        public virtual Especie Especie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen> Examen { get; set; }
        public virtual Raza Raza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacuna> Vacuna { get; set; }
    }
}
